# Study Jam 1 — Pengenalan ML
## Praktik 8 · Menyiapkan Google Colab dan Memuat Data
**Learning Path Machine Learning · GDGoC 2026–2027**

Notebook pendamping bagian 8 dari *MODUL LEARNING PATH GDGoC 2026-2027_MACHINE LEARNING*. Contoh kode pemuatan Iris mengikuti modul; penjelasan dan latihan singkat ditambahkan untuk memandu praktik.

Setelah praktik, kamu dapat:
- Membuka dan menjalankan notebook di Google Colab.
- Membedakan sel Teks, sel Kode, dan runtime.
- Memuat dataset Iris serta mengenali baris, fitur, dan label.

**Prasyarat:** akun Google, browser, dan dasar Python. CPU standar cukup untuk seluruh praktik ini. Tidak ada pelatihan model pada sesi ini.

## 8.1 Membuka dan menjalankan notebook

1. Buka [Google Colab](https://colab.research.google.com/) dan masuk dengan akun Google.
2. Unggah file `.ipynb` ini melalui pilihan **Upload notebook / Upload** pada dialog pembuka. Jika sudah terbuka dari tautan master, buat salinan ke Drive sendiri.
3. Simpan notebook ke Google Drive dan beri nama **Study Jam 1 - Pengenalan ML**.
4. Sambungkan runtime melalui tombol **Connect / Hubungkan**. Pilih CPU standar; GPU tidak diperlukan.
5. Jalankan sel kode berurutan dari atas dengan tombol ▶ atau **Shift+Enter**. Nama menu dapat berbeda menurut bahasa antarmuka.

Jika ingin mengikuti langkah pembuatan dari nol pada modul, buat notebook baru, gunakan nama yang sama, lalu salin sel teks dan kode dari notebook ini secara berurutan.

**Sel Teks (Markdown)** dipakai untuk judul, penjelasan, dan catatan. **Sel Kode** dipakai untuk menjalankan Python; hasilnya muncul di bawah sel. Klik dua kali sel teks berikut untuk mengubah tujuan belajarmu.

### Tujuan belajarku
Saya ingin dapat menjalankan kode Python di Google Colab dan memuat dataset Iris untuk mengenali fitur serta labelnya.

**Nama:** Egi Ratinsyah  
**Tanggal praktik:** 24/10/2026

### Jalankan kode Python pertamamu
Jalankan sel di bawah. Output yang diharapkan adalah `Halo, ML!`.

`print()` menampilkan teks atau nilai ke area output. Teks di dalam tanda kutip disebut *string*.

In [ ]:
print("Halo, ML!")

Halo, ML!

### Notebook dan runtime
Notebook adalah dokumen yang memuat teks, kode, dan output yang tersimpan. Runtime adalah mesin sementara yang menjalankan kode dan menyimpan variabel selama sesi aktif.

Menyimpan notebook ke Drive tidak berarti seluruh file sementara di runtime ikut tersimpan. Jika runtime terputus atau direset, variabel dapat hilang. Jalankan ulang sel dari atas jika muncul `NameError` karena variabel belum dibuat pada sesi tersebut.

**Coba sendiri:** ubah pesan pada sel sebelumnya menjadi sapaan dengan namamu, jalankan ulang, lalu kembalikan jika diperlukan.

## 8.2 Memuat dataset Iris

Iris berisi pengukuran **150 bunga** dari tiga jenis: `setosa`, `versicolor`, dan `virginica`. Setiap baris adalah satu contoh bunga.

| Kolom | Arti | Peran |
| --- | --- | --- |
| `sepal length (cm)` | Panjang kelopak bunga dalam cm | Fitur |
| `sepal width (cm)` | Lebar kelopak bunga dalam cm | Fitur |
| `petal length (cm)` | Panjang mahkota bunga dalam cm | Fitur |
| `petal width (cm)` | Lebar mahkota bunga dalam cm | Fitur |
| `species` | Jenis bunga | Label |

**Fitur** adalah informasi input; **label** adalah jawaban yang ingin diprediksi pada supervised learning. Jenis bunga merupakan kategori nominal: tidak ada urutan alami dari setosa ke virginica.

Dataset tersedia bersama scikit-learn, sehingga praktik ini tidak memerlukan unggahan CSV, pemasangan Drive, atau unduhan dataset terpisah.

### Langkah 1 · Memuat data sebagai tabel
Jalankan sel berikut terlebih dahulu.

- `load_iris` adalah fungsi untuk memuat dataset Iris.
- `as_frame=True` meminta representasi tabel pandas.
- `iris.frame.copy()` membuat salinan tabel dan menyimpannya sebagai `df` (*DataFrame*).

Pada tahap ini, tabel masih memiliki kolom `target` dengan kode kelas 0, 1, dan 2.

In [ ]:
from sklearn.datasets import load_iris

iris = load_iris(as_frame=True)
df = iris.frame.copy()

### Langkah 2 · Mengubah kode kelas menjadi nama jenis
`iris.target_names` menyimpan nama jenis bunga. `enumerate()` memasangkan urutan angka dengan nama, kemudian `dict()` membentuk pemetaan:

| Kode target | Nama jenis |
| --- | --- |
| 0 | setosa |
| 1 | versicolor |
| 2 | virginica |

`map()` mengganti kode pada `target` dengan nama jenis dan menaruhnya di kolom `species`. Setelah itu, `target` dihapus agar tabel akhir memiliki empat fitur dan satu label. Kode 0, 1, dan 2 menyatakan kategori, bukan tingkat atau besaran.

In [ ]:
df['species'] = df['target'].map(dict(enumerate(iris.target_names)))
df = df.drop(columns='target')

### Langkah 3 · Memeriksa ukuran dan nama kolom
`df.shape` menghasilkan pasangan `(jumlah_baris, jumlah_kolom)`. `df.columns.tolist()` menampilkan nama kolom sebagai list Python.

**Hasil yang diharapkan:** `(150, 5)`, yaitu 150 contoh bunga dan 5 kolom. Lima kolom tersebut terdiri atas **4 fitur + 1 label**, sehingga bukan berarti ada 5 fitur.

In [ ]:
print('Ukuran data:', df.shape)
print('Kolom:', df.columns.tolist())

Ukuran data: (150, 5)
Kolom: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)', 'species']

### Langkah 4 · Menampilkan lima baris pertama
`head()` hanya menampilkan lima baris pertama, bukan seluruh dataset. Angka indeks di paling kiri adalah penanda baris dan bukan salah satu dari lima kolom data.

Kelima baris pertama berlabel `setosa`. Itu tidak berarti seluruh dataset hanya berisi setosa; kita akan menghitung semua jenis pada langkah berikutnya.

In [ ]:
display(df.head(10))

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
5,5.4,3.9,1.7,0.4,setosa
6,4.6,3.4,1.4,0.3,setosa
7,5.0,3.4,1.5,0.2,setosa
8,4.4,2.9,1.4,0.2,setosa
9,4.9,3.1,1.5,0.1,setosa

### Langkah 5 · Menghitung contoh untuk setiap jenis
`df['species']` memilih kolom label. `value_counts()` menghitung kemunculan setiap nilai dalam kolom itu.

**Hasil yang diharapkan:** setosa 50, versicolor 50, dan virginica 50. Totalnya 150 bunga. Urutan tampilan kelas bukan hal utama; periksa nama dan jumlahnya.

In [ ]:
print('Jumlah per jenis:')
print(df['species'].value_counts())

Jumlah per jenis:
species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

### Membaca satu contoh bunga
Untuk memahami hubungan fitur dan label, lihat satu baris dengan `iloc[0]`. Python memakai indeks mulai dari nol, jadi indeks `0` menunjuk baris pertama.

Empat pengukuran pada baris itu adalah fitur milik satu bunga. `species` adalah label bunga yang sama.

In [ ]:
display(df.iloc[0])

sepal length (cm)       5.1
sepal width (cm)        3.5
petal length (cm)       1.4
petal width (cm)        0.2
species              setosa
Name: 0, dtype: object

## Latihan singkat

1. Tambahkan satu sel Kode dan tampilkan **10 baris pertama** dengan menyesuaikan contoh `head()`.
2. Tambahkan satu sel Teks lalu jawab:
   - Ada berapa baris dan kolom pada dataset?
   - Sebutkan empat fitur dan satu labelnya.
   - Mengapa `species` merupakan kategori, meskipun awalnya diwakili angka?
   - Mengapa lima baris pertama belum mewakili semua jenis bunga?
3. Tulis satu kalimat tentang perbedaan notebook yang tersimpan dengan runtime yang sedang aktif.

**Petunjuk:** `head(n)` menampilkan `n` baris pertama. Latihan ini cukup menggunakan data yang sudah dimuat; kamu belum perlu membuat atau melatih model.

In [ ]:
display(df.head(10))

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
5,5.4,3.9,1.7,0.4,setosa
6,4.6,3.4,1.4,0.3,setosa
7,5.0,3.4,1.5,0.2,setosa
8,4.4,2.9,1.4,0.2,setosa
9,4.9,3.1,1.5,0.1,setosa

In [ ]:
print('Ada berapa Baris dan Kolom dataset:', df.shape)
print('Kolom:', df.columns.tolist())
print('-----------------------------------------------')
print('Jumlah per jenis:')
print(df['species'].value_counts())
print('-----------------------------------------------')
print('Jumlah per jenis:')
print(df['species'].value_counts())

Ada berapa Baris dan Kolom dataset: (150, 5)
Kolom: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)', 'species']
-----------------------------------------------
Jumlah per jenis:
species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64
-----------------------------------------------
Jumlah per jenis:
species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

### Jawaban dan catatan peserta

- Jumlah baris dan kolom: 150 baris dan 5 kolom
- Empat fitur: sepal length (cm), sepal width (cm), petal length (cm), dan petal width (cm)
- Label: species
- Alasan species merupakan kategori: Karena angka 0, 1, dan 2 hanya berupa kode/label untuk membedakan jenis bunga (setosa, versicolor, virginica) dan tidak memiliki nilai matematis atau tingkatan.
- Alasan lima baris pertama belum mewakili semua jenis: Karena data tersusun secara berurutan berdasarkan jenisnya, sehingga 5 baris pertama semuanya hanya berisi bunga jenis setosa.
- Perbedaan notebook dan runtime: Notebook adalah file tempat menyimpan kode dan teks, sedangkan runtime adalah mesin/sistem aktif di server yang menjalankan kode Python tersebut.

## Jika menemui kendala

| Kendala | Langkah yang dapat dicoba |
| --- | --- |
| Sel belum berjalan | Sambungkan runtime, lalu tekan ▶ atau Shift+Enter. |
| `NameError: name 'df' is not defined` | Jalankan kembali sel dari Langkah 1 secara berurutan. |
| `KeyError: 'target'` setelah mengulang Langkah 2 | Kolom target sudah dihapus. Jalankan ulang Langkah 1, lalu Langkah 2. |
| `ModuleNotFoundError: No module named 'sklearn'` | Pada sel baru, jalankan `%pip install scikit-learn pandas`, lalu ulangi pemuatan data. Langkah instalasi biasanya tidak diperlukan di Colab. |
| Hanya terlihat lima bunga | `head()` memang membatasi tampilan. Periksa `df.shape` untuk ukuran seluruh dataset. |
| Variabel hilang setelah runtime direset | Jalankan kembali semua sel kode dari atas. |